package universidadejemplo.Vistas;

import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Andres Chico
 */
public class UniversidadULP extends javax.swing.JFrame {

    /**
     * Creates new form UniversidadULP
     */
    public UniversidadULP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        formA = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        fm = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        fi = new javax.swing.JMenuItem();
        mn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        porMateria = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumnos");

        formA.setText("Formulario de Alumno");
        formA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formAActionPerformed(evt);
            }
        });
        jMenu1.add(formA);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");

        fm.setText("Formulario de materias");
        fm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmActionPerformed(evt);
            }
        });
        jMenu2.add(fm);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administracion");

        fi.setText("Formulario de inscripcion");
        fi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiActionPerformed(evt);
            }
        });
        jMenu3.add(fi);

        mn.setText("Manipulacion de notas");
        mn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnActionPerformed(evt);
            }
        });
        jMenu3.add(mn);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        porMateria.setText("Alumnos por materia");
        porMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(porMateria);

        jMenuBar1.add(jMenu4);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        salir.add(jMenuItem1);

        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formAActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        Alumnos fa=new Alumnos();
        fa.setVisible(true);
        Escritorio.add(fa);
        Escritorio.moveToFront(fa);
    }//GEN-LAST:event_formAActionPerformed

    private void fiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        Inscripciones ins=new Inscripciones();
        ins.setVisible(true);
        Escritorio.add(ins);
        Escritorio.moveToFront(ins);
    }//GEN-LAST:event_fiActionPerformed

    private void fmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        Materias m=new Materias();
        m.setVisible(true);
        Escritorio.add(m);
        Escritorio.moveToFront(m);
        
    }//GEN-LAST:event_fmActionPerformed

    private void mnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        Notas mn=new Notas();
        mn.setVisible(true);
        Escritorio.add(mn);
        Escritorio.moveToFront(mn);
    }//GEN-LAST:event_mnActionPerformed

    private void porMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porMateriaActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        porMateria pm=new porMateria();
        pm.setVisible(true);
        Escritorio.add(pm);
        Escritorio.moveToFront(pm);
    }//GEN-LAST:event_porMateriaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
         
    }//GEN-LAST:event_salirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(this, "Estás seguro que quieres salir?","Cerrar Ventana", JOptionPane.YES_NO_OPTION);
        
        if(respuesta==JOptionPane.YES_OPTION){
            
            this.dispose();//cierro la ventana
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniversidadULP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniversidadULP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniversidadULP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniversidadULP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UniversidadULP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem fi;
    private javax.swing.JMenuItem fm;
    private javax.swing.JMenuItem formA;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mn;
    private javax.swing.JMenuItem porMateria;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables




}
